version: '3.4'

services:
  dev:
    image: ${DOCKER_REGISTRY-}dev
    build:
      context: .
      dockerfile: dev/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=yourdb;Username=youruser;Password=yourpassword