version: '3.4'

services:
  dev:
    image: ${DOCKER_REGISTRY-}dev
    build:
      context: .
      dockerfile: dev/Dockerfile
    ports:
      - "80:80"
  db:
    container_name: db_postgres
    image: postgres
    environment:
      - POSTGRES_DB=eclipto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always